### ISSUE TITLE
SYS_CONTEXT('userenv','DBLINK_INFO')

### ISSUE THREAD

**Issue by simonpane** [method5/method5#27]
You could leverage "`SYS_CONTEXT('userenv','DBLINK_INFO') IS NOT NULL`" for target databases that are **11.2 or higher** as an additional safety check to the sys.m5_prevent_direct_logon trigger.

**Comment by jonheller1** [comment]
Great idea, thanks for creating this issue!  This will help prevent someone connecting directly if they had the password and were using the right host.

**Comment by simonpane** [comment]
Yes but as mentioned it's only for 11.2 and above.

For <= 11.1 you can use `SYS_CONTEXT('userenv','MODULE') like 'oracle@%'` to detect an incomming connection from a DB_LINK.  This is better than nothing but i**s still quite weak** as someone can easily by-pass it with `DBMS_APPLICATION_INFO.set_module` .

**Comment by jonheller1** [comment]
You're right, this won't be perfect.  But keep in mind that this is like the 4th layer of defense for this application.  To get to the point of trying to directly connect as Method5, a user must have broken into a database or host, gotten DBA or SYSDBA privileges (depending on the version) to get a hash, and also decrypted a password hash (and when possible the weaker DES password hash is removed).

**Comment by jonheller1** [comment]
@simonpane I added your idea into the new version 8.0.2.  Thanks again for creating this issue.  If you find anything else, or have any comments, you can add another issue or email me at hjon@ventechsolutions.com.  I've only tested this on Oracle 11.2 and 12.1; it wouldn't surprise me if there are some more issues with older versions.
