### ISSUE TITLE
Compare Everything Everywhere - Java Source potential issue

### ISSUE THREAD

**Issue by zhudock** [method5/method5#58]
To be honest, I have not actually run anything in Method5, but was recently working on a very similar project.

In all the permutations I've tried, running `dbms_metatdata.get_ddl()` on a JAVA_SOURCE object would spit out all code on a single line that was unreadable and wouldn't compile. 

All other object types seemed to behave as expected, but we assembled our JAVA_SOURCE using an `xmlagg()` (since listagg can't output a CLOB) on the `all_source` view

**Comment by jonheller1** [comment]
@zhudock Can you give me an example of GET_DDL not working?  I tried it on a few JAVA_SOURCEs and it seems to work OK for me.

Below is a fully reproducible test case where everything looks OK.  This was run on Windows 7 command prompt, with SQL*Plus 11.2.0.3 against Oracle 12.1.0.2 on Solaris.

Maybe it's a client issue.  What Oracle program, client, and OS are you using?  It may also be a SQL*Plus setting issue.  You may want to check your login.sql or glogin.sql.

Below are the commands in my login.sql:

```
set serveroutput on size unlimited
set trimspool on
set long 5000
set linesize 130
set pagesize 9999
set termout off
set sqlprompt "_user'@'_connect_identifier> "
set termout on
```

Here's my code and output:

```
> create or replace java source named "JavaTest" as
  2  public class JavaTest
  3  {
  4    public static String create()
  5    {
  6      return "asdf";
  7    }
  8  }
  9  /

Java created.

> set long 10000000
> select dbms_metadata.get_ddl('JAVA_SOURCE', 'JavaTest', user) from dual;

DBMS_METADATA.GET_DDL('JAVA_SOURCE','JAVATEST',USER)
--------------------------------------------------------------------------------

   CREATE JAVA SOURCE NAMED "JHELLER_DBA"."JavaTest" AS
 public class JavaTest
{
  public static String create()
  {
    return "asdf";
  }
}


> create or replace function JavaTest return varchar2 as language java
  2  name 'JavaTest.create() return java.lang.String';
  3  /

Function created.

> select JavaTest from dual;

JAVATEST
----------------------------------------------------------------------------------------------------------------------------------
asdf

```

Hope that helps.  This might make a good StackOverflow question.  If you post it there send me a link so I can take a look at it.  Or you can just respond here.

By-the-way, I'm thinking of re-arranging the code a bit.  The Compare Everything Everywhere script has grown a lot and probably deserves being split up into a a separate "Add ons" directory, and broken into a single file for the procedure, or something like that.  So the file may move in the near future.

Also, I'd be curious to know what project you're working on that's similar to mine.

Thanks,
Jon

**Comment by zhudock** [comment]
I get the same results in SQL*Plus, SQLcL and Toad on Win 7 and Win 10. Any JAVA_SOURCE objects in our schema are returned as a block of 1 to 5 lines that seem to apply the line-break arbitrarily, even mid-word in some cases, and always resulting in code that won't compile.  I'll dig deeper into the configurations.

My project in no way intends to compete with Method5, I was given a task at work to build a solution to compare a certain schema across several databases, and my implementation ended up being very similar to the Compare Everything Everywhere script.

**Comment by jonheller1** [comment]
@zhudock I'm going to close this issue.  Let me know if you can reproduce this metadata problem or find some other problem with the Compare Everything Everywhere code.  Thanks.
