### ISSUE TITLE
select method5.method5_admin.generate_remote_install_script() from dual; does not generate script

### ISSUE THREAD

**Issue by normlass** [method5/method5#62]
Might be something dumb, but can't seem to generate this install script for my remote databases...

All I get is something like this:

--Install Method5 on remote target.
--

**Comment by jonheller1** [comment]
@normlass  What program did you use to generate the script?  The result is a large CLOB, which may not display properly in tools like SQL*Plus.  If you run it in a program like Toad or SQL Developer it should return as a single, large value, that you can save to a file.

**Comment by normlass** [comment]
I used SQL Developer, I've saved the output and all get is that single line you see in sql developer...

I've attached a screenshot...

Thanks,

<img width="309" alt="m5_remoteinstallscript_screenshot" src="https://user-images.githubusercontent.com/44781081/48013084-88b36b00-e0f1-11e8-9d10-bfbd962d8564.PNG">

**Comment by jonheller1** [comment]
@normlass Use the green arrow "Run Statement" button, not the "Run Script" button.  I don't know why, but SQL*Plus and SQL Developer Run Script default to only show a small number of values for CLOBs.

I added that note to administer_method5.md, to make this clearer for future users.

I hope that helps.  Let me know if you're still running into any problems.

Thanks,
Jon

**Comment by normlass** [comment]
Ahh... Thanks... That worked!

Knew it was something dumb :)
