### ISSUE TITLE
odd default database selection happening when querying v$resource_limit

### ISSUE THREAD

**Issue by normlass** [method5/method5#66]
Hi Jon,

Can't explain why this is happening, but I'm trying to find max processes used and limit set from v$resource_limit and I'm getting an odd database selection coming back can't figure out why...

working in a test environment I run

select * from table(m5(q'[ select status from v$instance ]'))

and I get

```
DATABASE_NAME                  STATUS      
------------------------------ ------------
db1                         OPEN        
db2                         OPEN        
db3                          OPEN        
db4                           OPEN      
```  

as expected... 

then I run:

select * from table(m5(q'[ select * from v$resource_limit where resource_name = 'processes' ]'));

and I only get 

```
DATABASE_NAME                  RESOURCE_NAME                  CURRENT_UTILIZATION MAX_UTILIZATION INITIAL_ALLOCATION                       LIMIT_VALUE                             
------------------------------ ------------------------------ ------------------- --------------- ---------------------------------------- ----------------------------------------
db2                        processes                                       44              53       1200                                     1200                              
db3                          processes                                       44              53       1200                                     1200                              

```

but if I add in db4 as a target I do get the results expected

```
select * from table(m5(q'[ select * from v$resource_limit where resource_name = 'processes' ]','db4'));

DATABASE_NAME                  RESOURCE_NAME                  CURRENT_UTILIZATION MAX_UTILIZATION INITIAL_AL LIMIT_VALU     CON_ID
------------------------------ ------------------------------ ------------------- --------------- ---------- ---------- ----------
db4                           processes                                      115             126        300        300          0

```

if you got time, can you provide some insight as to why this happening?

thanks,

**Comment by jonheller1** [comment]
@normlass  This problem is described in the user guide here: https://github.com/method5/method5/blob/master/user_guide.md#version_star

You can fix it by using the `**` option, like this:

`select * from table(m5(q'[ select ** from v$resource_limit where resource_name = 'processes' ]'));`

The version star will get the lowest-common-denominator of columns.  Usually `CON_ID` is the only different column, and we usually don't care about it.

Let me know if that works for you.

Thanks,
Jon

**Comment by normlass** [comment]
Not so odd afterall..  THANKS! sorry must have missed that point in documentation, or didn't put 2 and 2 together!

It worked fine with **.
