### ISSUE TITLE
Support databases with same DB_NAME and same DB_DOMAIN

### ISSUE THREAD

**Issue by zhudock** [method5/method5#67]
Suggestion for the procedure method5_admin.create_user

use
`lower(sys_context('userenv', 'db_unique_name'))`

instead of
`lower(sys_context('userenv', 'db_name'))`

[DB_UNIQUE_NAME](https://docs.oracle.com/cd/B19306_01/server.102/b14237/initparams056.htm#REFRN10242)

**Comment by jonheller1** [comment]
@zhudock Good idea.  Although I might just skip the whole DB_NAME mess and just check "does the user already exist" instead.

**Comment by jonheller1** [comment]
Fixed in dev branch.
