### ISSUE TITLE
expand m5_database.hostname

### ISSUE THREAD

**Issue by zhudock** [method5/method5#69]
v$instance_name reports that host_name is a varchar2(64 byte). m5_database is limited to varchar2(15 char)

**Comment by jonheller1** [comment]
@zhudock,

The values in M5_DATABASE are used to create database link names, so the names have some additional size and value restrictions.

But the values in M5_DATABASE are only aliases.  You can call the database or host name whatever you want, and then use the real name when you customize the database links in the administration steps.

On the dev branch I added a note to the install_method.md file, to make this clearer during installation.  Let me know if that's good enough or if you still have problems.

I'm a little behind on Method5 updates, but I'll get to all of your issues eventually.  (I assume you've been able to workaround these issues, but if any of them are roadblocks preventing you from using the program, please let me know and I'll look at them sooner.)

Thanks,
Jon

**Comment by zhudock** [comment]
Thanks. I think the additional note in the dev branch will be sufficient.

We have been able to work around the issues and things are working quite nicely so far.
