### ISSUE TITLE
Global data dictionary tables are not being updated

### ISSUE THREAD

**Issue by mashoaib4m5** [method5/method5#74]
Hi,
I noticed that the tables like DBA_USERS are not being updated ( as per schedule they supposed to be refreshed every night).

Please let me know what to check and how to enable / resume the schedule.

One DBA, who used to take care of Method5, has retired and left the company and we have dropped his ID from all databases, but in the M5_DBA_USERS still shows his ID.

Thanks and regards,

Muhammad Shoaib

**Comment by jonheller1** [comment]
@mashoaib4m5,

You probably just need to recreate the jobs as a user who is active and configured to use Method5.

First, remove the existing jobs by running the PL/SQL block here: https://github.com/method5/method5/blob/master/code/remove_method5_global_data_dictionary.sql

Then run this SQL*Plus script to recreate the jobs under your active account: https://github.com/method5/method5/blob/master/code/install_method5_global_data_dictionary.sql

The files are SQL*Plus scripts and are normally run from a specific directory during installation. But if you don't want to download the whole thing, and find the right directory, you can simply remove the line "@code/check_user must_be_m5_user" and run them from anywhere.

I hope that helps. Let me know if you're still having problems.

Thanks,
Jon

**Comment by mashoaib4m5** [comment]
Hi Jon,

Thanks for the prompt response.

I ran from your query to extract jobs:

		select owner||'.'||job_name job_name
		from dba_scheduler_jobs
		where job_name in
		(
			'M5_DBA_USERS_JOB',
			'M5_V$PARAMETER_JOB',
			'M5_PRIVILEGES_JOB',
			'M5_USER$_JOB'
		)
		order by 1

It showed 0 jobs, so I removed all filters and just ran:

select owner||'.'||job_name job_name
		from dba_scheduler_jobs
        order by owner,job_name

so got this result - I replaced our users' name with USER# and left Method5 and SYS users, please let me know which job should be deleted and recreated  (btw what are M5_LINK_REFRESH_JOB in every schema for ?):


JOBS | ENABLED | STATUS
-- | -- | --
USER1.M5_LINK_REFRESH_JOB | FALSE | DISABLED
USER2.M5_LINK_REFRESH_JOB | FALSE | DISABLED
USER3.M5_LINK_REFRESH_JOB | FALSE | DISABLED
USER4.M5_LINK_REFRESH_JOB | FALSE | DISABLED
USER5.M5_LINK_REFRESH_JOB | FALSE | DISABLED
USER6.M5_DBDEVS_1414271 | TRUE | RUNNING
USER6.M5_DBDEVS_1414375 | TRUE | RUNNING
USER6.M5_DBDEVS_1414693 | TRUE | RUNNING
USER6.M5_DBDEVS_1414797 | TRUE | RUNNING
USER6.M5_LINK_REFRESH_JOB | FALSE | DISABLED
USER6.M5_DBDEVS_1414291 | TRUE | RUNNING
USER6.M5_DBDEVS_1414395 | TRUE | RUNNING
USER6.M5_DBDEVS_1414713 | TRUE | RUNNING
USER6.M5_DBDEVS_1414817 | TRUE | RUNNING
USER6.M5_DBTSTS_1414292 | TRUE | RUNNING
USER6.M5_DBTSTS_1414396 | TRUE | RUNNING
USER6.M5_DBTSTS_1414714 | TRUE | RUNNING
USER6.M5_DBTSTS_1414818 | TRUE | RUNNING
USER7.M5_LINK_REFRESH_JOB | FALSE | DISABLED
METHOD5.BACKUP_M5_DATABASE_JOB | FALSE | BROKEN
METHOD5.CLEANUP_M5_TEMP_TABLES_JOB | FALSE | BROKEN
METHOD5.CLEANUP_M5_TEMP_TRIGGERS_JOB | FALSE | BROKEN
METHOD5.DIRECT_M5_GRANTS_JOB | FALSE | BROKEN
METHOD5.EMAIL_M5_DAILY_SUMMARY_JOB | FALSE | DISABLED
METHOD5.SNARE_DAILY_JOB | FALSE | DISABLED
METHOD5.STOP_TIMED_OUT_JOBS_JOB | FALSE | BROKEN
USER8.M5_DBDEVS_1414957 | TRUE | RUNNING
USER8.M5_LINK_REFRESH_JOB | FALSE | DISABLED
USER8.M5_DBDEVS_1414977 | TRUE | RUNNING
USER8.M5_DBTSTS_1414978 | TRUE | RUNNING
USER9.M5_LINK_REFRESH_JOB | FALSE | DISABLED
USER0.M5_LINK_REFRESH_JOB | FALSE | DISABLED
USER.M5_LINK_REFRESH_JOB | FALSE | DISABLED
SYS.BSLN_MAINTAIN_STATS_JOB | TRUE | SCHEDULED
SYS.CLEANUP_NON_EXIST_OBJ | TRUE | SCHEDULED
SYS.CLEANUP_ONLINE_IND_BUILD | TRUE | SCHEDULED
SYS.CLEANUP_ONLINE_PMO | TRUE | SCHEDULED
SYS.CLEANUP_TAB_IOT_PMO | TRUE | SCHEDULED
SYS.CLEANUP_TRANSIENT_PKG | TRUE | SCHEDULED
SYS.CLEANUP_TRANSIENT_TYPE | TRUE | SCHEDULED
SYS.DRA_REEVALUATE_OPEN_FAILURES | TRUE | SCHEDULED
SYS.FGR$AUTOPURGE_JOB | FALSE | DISABLED
SYS.FILE_SIZE_UPD | TRUE | SCHEDULED
SYS.FILE_WATCHER | FALSE | DISABLED
SYS.HM_CREATE_OFFLINE_DICTIONARY | FALSE | DISABLED
SYS.LOAD_OPATCH_INVENTORY | FALSE | DISABLED
SYS.ORA$AUTOTASK_CLEAN | TRUE | SCHEDULED
SYS.PMO_DEFERRED_GIDX_MAINT_JOB | TRUE | SCHEDULED
SYS.PURGE_LOG | TRUE | SCHEDULED
SYS.RSE$CLEAN_RECOVERABLE_SCRIPT | TRUE | SCHEDULED
SYS.SM$CLEAN_AUTO_SPLIT_MERGE | TRUE | SCHEDULED
SYS.XMLDB_NFS_CLEANUP_JOB | FALSE | DISABLED

Can I just run your script to create the job in SYS or Method5 user?

Thanks again for reply.

Shoaib

**Comment by mashoaib4m5** [comment]
Please note that the user WS is not in the list who used to take care of it and now has gone and we have dropped his ID - so maybe he had the jobs in his schema. If that is the case, can I run your script to create the jobs in SYS or Method5 schema?

Thanks.

Shoaib

**Comment by mashoaib4m5** [comment]
sorry, pressed the Close and Comment button, not knowing that it would consider at the issue is closed.

Thanks.

Shoaib

**Comment by jonheller1** [comment]
Shoaib,

Yes, you can simply re-run the script to create the new jobs. However, you must run the script as a configured user, not as METHOD5 or SYS. (I know this is kind of annoying, but for security purposes the program avoids using shared accounts.)

You can ignore all of the other jobs you listed, they all have a purpose. M5_LINK_REFRESH_JOB is used to modify database links on each user's schema. This way, for example, if the admin changes a database link password, that change will get copied to every user's schema. (If I remember correctly, I had to use jobs for that task because there's no way to directly create or modify database links on other user's schemas.)

Thanks,
Jon

**Comment by mashoaib4m5** [comment]
Hi Jon,

I created the jobs in my schema and they are running. Awesome. Thanks for your help.

Closing the issue now.

Take care

Shoaib
